// ======================= PROJECT DATA =======================
const projects = [
    { title: "Solitude in Motion", year: "2025", category: "Fashion Editorial", client: "Maison Noir", description: "An exploration of stillness within movement, captured across abandoned industrial spaces in northern France.\nThe series investigates the tension between haute couture and raw urban decay, creating a visual dialogue that challenges conventional fashion photography.\nEach frame was composed to evoke a sense of timeless elegance against the passage of industrial history.\nShot over three weeks in winter light, the project embraces imperfection as a form of beauty.\nNatural textures of rust, concrete, and aged wood become the backdrop for meticulously crafted garments.\nThe result is a body of work that transcends seasonal trends and speaks to something deeper.\nThe quiet poetry of spaces left behind, reimagined through the lens of contemporary fashion.", tags: ["Fashion", "Film", "Noir"], link: "#" },
    { title: "Concrete Poetry", year: "2024", category: "AI Production", client: "Detroit Archive", description: "Generative imagery trained on brutalist architecture and classical sculpture, merging centuries of artistic tradition with cutting-edge neural networks.\nThis project explores how artificial intelligence can reinterpret the weight and gravity of concrete structures through the lens of Renaissance proportions.\nEvery output was curated from thousands of iterations, selecting only those that captured genuine emotional resonance.\nThe process itself became a meditation on creativity — asking what happens when a machine learns to see beauty in brutalism.\nCollaborating with architects and art historians, we developed a visual language that feels both ancient and impossibly futuristic.\nThe final collection of 200 images was exhibited across three European galleries.\nA new chapter in the dialogue between human intuition and artificial imagination.", tags: ["AI", "Architecture", "Experimental"], link: "#" },
    { title: "Glass & Shadow", year: "2025", category: "Campaign", client: "Vogue Italia", description: "Spring campaign exploring transparency and opacity in contemporary fashion, where light itself becomes the primary material.\nShot across Milan's modernist glass pavilions, each composition plays with refraction, reflection, and the dissolving boundary between garment and environment.\nThe creative direction drew inspiration from James Turrell's light installations and Olafur Eliasson's atmospheric sculptures.\nModels moved through spaces where shadow and illumination constantly shifted, creating unrepeatable moments captured in-camera.\nPost-production was deliberately minimal — the magic was engineered on set through precise choreography of natural and artificial light.\nSeven looks, seven locations, each telling a story of revelation and concealment.\nA meditation on what it means to be seen and unseen in the age of total visibility.", tags: ["Campaign", "Editorial", "Fashion"], link: "#" },
    { title: "The Weight of Light", year: "2024", category: "Motion", client: "Self-Initiated", description: "A study of how light behaves across different materials and surfaces, documented through slow-motion cinematography at 1000 frames per second.\nThis self-initiated research project became an obsession with the invisible — capturing the exact moment when light transforms a surface from mundane to extraordinary.\nOver six months, we filmed in laboratories, cathedrals, underwater caves, and open deserts.\nThe resulting footage reveals a hidden world where photons dance across silk, shatter through crystal, and pool in the hollows of human skin.\nEach sequence is accompanied by a bespoke sound design that translates light wavelengths into audible frequencies.\nThe project challenges the viewer to slow down and witness what the naked eye can never see.\nPresented as an immersive installation with synchronized surround sound.", tags: ["Motion", "Research", "Light"], link: "#" },
    { title: "Archive 03: Noir", year: "2025", category: "Editorial", client: "Numéro", description: "Third installment of the ongoing noir archive, featuring 40 unseen frames that push the boundaries of monochrome fashion photography.\nDrawing from the visual vocabulary of film noir cinema, each image constructs a narrative of mystery, desire, and quiet menace.\nThe series was shot entirely at night across Paris, using only practical lighting — street lamps, neon signs, and the glow of passing cars.\nModels become characters in an unwritten screenplay, their expressions carrying the weight of untold stories.\nThis archive represents three years of nocturnal exploration, building a visual encyclopedia of darkness as a creative tool.\nThe work has been acquired by the Centre Pompidou for their permanent photography collection.\nA testament to the enduring power of shadow in an age of relentless illumination.", tags: ["Archive", "Fashion", "Noir"], link: "#" },
    { title: "Fragments", year: "2023", category: "Campaign", client: "Acne Studios", description: "AW23 campaign celebrating imperfection and the beauty of broken forms, where garments are presented as sculptures in various states of deconstruction.\nThe creative concept emerged from conversations about wabi-sabi philosophy and its relevance to contemporary Scandinavian design.\nEach photograph captures a moment of beautiful disruption — fabric caught mid-tear, buttons scattered like constellations, seams revealing their inner architecture.\nThe campaign was shot in a single day at a demolished textile factory outside Stockholm.\nRather than fighting the chaos of the location, we embraced it, allowing debris and destruction to frame moments of unexpected grace.\nThe result redefines what a luxury fashion campaign can look like.\nBeauty found not in perfection, but in the courage to break apart and begin again.", tags: ["Campaign", "Fashion", "Movement"], link: "#" },
    { title: "Static Bloom", year: "2025", category: "AI Production", client: "Prada", description: "Floral abstractions through custom neural networks trained on 400 years of botanical illustrations from the Royal Botanical Gardens archive.\nEach generated image preserves the scientific precision of historical botanical art while introducing impossible colors, geometries, and mutations.\nThe collaboration with Prada focused on translating these AI-generated botanicals into textile patterns for their SS25 collection.\nWorking closely with the Fondazione Prada's research team, we developed a proprietary training methodology that respects the integrity of source material.\nThe project produced over 3,000 unique compositions, of which 12 were selected for production.\nIt represents a new paradigm in the relationship between heritage craft and artificial intelligence.\nWhere the garden of the past meets the algorithms of the future.", tags: ["AI", "Nature", "Fashion"], link: "#" },
    { title: "Silent Hours", year: "2024", category: "Film", client: "Loewe", description: "Short film exploring the quiet moments between fashion seasons, when ateliers fall silent and garments hang waiting for their moment.\nShot over 72 continuous hours inside Loewe's Madrid workshop, the film captures the poetry of empty spaces still charged with creative energy.\nScissors rest mid-cut, threads hang suspended, and mannequins stand like sentinels guarding unfinished dreams.\nThe cinematography employs extremely long takes and imperceptible camera movements that mirror the slow breathing of a sleeping building.\nSound design amplifies the whisper of fabric settling, the tick of cooling sewing machines, and the distant hum of the city outside.\nThe film premiered at the Venice Film Festival and has since been screened at 14 international festivals.\nA love letter to the spaces where beauty is born in silence.", tags: ["Film", "Fashion", "Biennale"], link: "#" },
    { title: "Marble & Memory", year: "2025", category: "Editorial", client: "AnOther Magazine", description: "Classical sculpture reinterpreted through contemporary lens, creating a visual bridge between ancient Greek ideals and modern fashion.\nShot in the sculpture halls of the Louvre after hours, models posed alongside masterworks spanning two millennia.\nThe editorial explores how our understanding of physical perfection has evolved — and how it hasn't.\nEach pairing was researched with art historians to find unexpected dialogues between ancient marble and contemporary couture.\nThe lighting was designed to match the original museum conditions, creating an uncanny sense of shared temporal existence.\nTwelve spreads, twelve conversations across centuries of human aspiration toward beauty.\nA reminder that the desire to adorn and transform the body is as old as civilization itself.", tags: ["Editorial", "Art", "Sculpture"], link: "#" },
    { title: "Threshold", year: "2024", category: "Campaign", client: "Bottega Veneta", description: "Liminal spaces and transitional states become the conceptual framework for Bottega Veneta's resort collection campaign.\nPhotographed in airports, train stations, hotel lobbies, and ferry terminals across the Mediterranean.\nEach image captures the exquisite tension of being between destinations, speaking to the modern luxury consumer.\nEvery location was chosen for its architectural quality of in-betweenness — spaces designed for passing through, not staying.\nModels carry Bottega's signature pieces as talismans of identity in anonymous spaces.\nThe art direction strips away all conventional fashion campaign signifiers, presenting luxury as a state of mind.\nShot on medium format film for a tactile, timeless quality that resists the ephemeral nature of digital imagery.", tags: ["Campaign", "Luxury", "Space"], link: "#" },
    { title: "Nocturne", year: "2025", category: "Fashion Editorial", client: "Harper's Bazaar", description: "Night-time editorial across three European capitals over a single lunar cycle, documenting fashion under the influence of moonlight.\nBeginning in Berlin at the new moon, continuing through Paris at the half moon, and concluding in Rome under a full moon.\nEach city brought its own character — Berlin's industrial minimalism, Paris's romantic geometry, Rome's baroque excess.\nThe wardrobe evolved in parallel, from severe architectural silhouettes to flowing, luminous gowns.\nNight shooting presented extraordinary technical challenges that pushed our team to develop new lighting techniques.\nCustom-built diffusion panels captured and redirected moonlight onto subjects with ethereal precision.\nThe complete series spans 48 images across 16 editorial pages of pure nocturnal magic.", tags: ["Fashion", "Night", "Editorial"], link: "#" },
    { title: "Residue", year: "2024", category: "AI Production", client: "Balenciaga", description: "Post-digital aesthetics exploring the aftermath of creation, where AI-generated imagery is deliberately degraded and reconstructed.\nThis project for Balenciaga investigates what remains when perfection is systematically destroyed — the residue of creative intention.\nEach image began as a flawless AI generation before being subjected to custom corruption algorithms inspired by glitch art.\nThe resulting visuals capture Demna's vision of fashion as a site of productive destruction.\nWorking with Balenciaga's design team, we created a visual language that mirrors the house's deconstructive approach.\nThe campaign was distributed exclusively through digital channels, each image programmed to further degrade with each share.\nBeauty as entropy — the most honest representation of how images live and die in the digital age.", tags: ["AI", "Luxury", "Experimental"], link: "#" },
    { title: "Paper Cities", year: "2023", category: "Motion", client: "Hermès", description: "Stop-motion urban landscapes through paper architecture, creating miniature cities from Hermès packaging materials.\nOver 14 weeks, a team of 8 paper artists constructed a scaled metropolis entirely from orange boxes, tissue paper, and ribbon.\nEach scene was photographed frame by frame — 24 frames per second, 18,000 frames total — to bring the paper city to life.\nHermès scarves became flowing rivers, belts transformed into elevated highways, and watches served as public clocks.\nThe project celebrates craftsmanship at every scale, from microscopic paper folds to grand architectural vision.\nThe final film runs 12 minutes and was premiered at the Hermès flagship on Rue du Faubourg Saint-Honoré.\nA testament to the extraordinary things that happen when patience meets imagination.", tags: ["Motion", "Art", "Architecture"], link: "#" },
    { title: "Still Water", year: "2025", category: "Editorial", client: "Dazed", description: "Reflections and stillness in natural water bodies become the canvas for an editorial exploring fashion's relationship with nature.\nShot across seven lakes in Scandinavia, each location was chosen for its unique reflective qualities and water color.\nModels stood at the water's edge or waded into shallow pools, their reflections creating doubled compositions.\nThe styling deliberately chose fabrics that respond to moisture — silks that cling, wools that darken, cottons that become translucent.\nThis interplay between garment and element created genuinely unrepeatable images where nature became the ultimate styling tool.\nEnvironmental sustainability informed every production decision, from carbon-neutral travel to biodegradable set materials.\nFashion as communion with the natural world, not conquest of it.", tags: ["Editorial", "Nature", "Film"], link: "#" },
    { title: "Velvet Archive", year: "2024", category: "Campaign", client: "Gucci", description: "Textures and textiles from five decades of fashion are excavated from Gucci's historic archive in Florence.\nEach piece photographed with the reverence of archaeological discovery, presenting vintage garments as living documents of creative evolution.\nShot in the archive's temperature-controlled vaults using macro lenses, every weave, stitch, and pattern is rendered in extraordinary detail.\nThe accompanying text traces the provenance of each piece — who designed it, who wore it, and the cultural moment it embodied.\nClose-up photography reveals the human touches embedded in luxury craftsmanship: a slightly uneven hand-stitch, a maker's mark hidden inside a lining.\nThe gentle wear patterns tell stories of lives lived beautifully, each crease a chapter in an unwritten memoir.\nThe campaign culminated in a limited-edition book published by Steidl, now in its third printing.", tags: ["Campaign", "Archive", "Textile"], link: "#" }
];

const mockImages = [
    'asset/pics/Mockup.webp',
    'asset/pics/9D6BE2F7-0FB4-404F-B5CC-BF0AAD47599A.webp',
    'asset/pics/Brand Guidelines 1.0_0.webp',
    'asset/pics/Brand Guidelines 1.0_0_png.webp',
    'asset/pics/Coaster.webp',
    'asset/pics/Gearlab.webp',
    'asset/pics/Hako-10_0.webp',
    'asset/pics/Hako-12_0.webp',
    'asset/pics/Hako-5.webp',
    'asset/pics/HAKO64541_0.webp',
    'asset/pics/Kodangs Mockup33_0.webp',
    'asset/pics/Kodangs-1_0.webp',
    'asset/pics/Kodangs-2_0.webp',
    'asset/pics/Kodangs-3_0.webp',
    'asset/pics/Kozen 3.webp'
];
projects.forEach((p, i) => { p.image = mockImages[i % mockImages.length]; });
projects[0].image = 'asset/pics/Gearlab.webp';

const galleryExtra = [
    'asset/pics/Kozen31.webp',
    'asset/pics/Kozen4.webp',
    'asset/pics/Large Ice Tray-1.jpg.webp',
    'asset/pics/Large Ice Tray-2.jpg.webp',
    'asset/pics/Large Ice Tray-5.jpg.webp',
    'asset/pics/Mockup 3.webp',
    'asset/pics/Mockup-7.webp',
    'asset/pics/Orthomedix Final Design 1_0.webp',
    'asset/pics/Orthomedix Final Design 2_0.webp',
    'asset/pics/Orthomedix Final Design 3_0.webp',
    'asset/pics/Screenshot 2569-06-15 at 13.50.32.webp',
    'asset/pics/Star Ice Tray-1.webp',
    'asset/pics/Star Ice Tray-4.webp',
    'asset/pics/Stellar Logo Mockup 2.webp',
    'asset/pics/Ultraxonic 57.webp',
    'asset/pics/Ultraxonic 88.webp'
];
